### ISSUE TITLE
can i get a subdomain?

### ISSUE THREAD

**Issue by kokofixcomputers** [StioStudio/share#1]
Can i please get a subdomain? i just want a personal website and upload some html files

**Comment by StioStudio** [comment]
> Can i please get a subdomain? i just want a personal website and upload some html files

Yeah sure

**Comment by StioStudio** [comment]
Go to https://github.com/settings/pages
Then click `add domain`

**Comment by StioStudio** [comment]
Then write `name-of-sub-domain.stio.studio`. Just change name-of-sub-domain to what you want.
Then give me the TXT values
